# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: './src/*/*.*.Test.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: Bash@3
  displayName: Docker Login
  inputs:
    targetType: 'inline'
    script: |
      docker login docker.pkg.github.com --username bryht
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker tag domino-application docker.pkg.github.com/playdomino/domino-application/domino-application:dev
- task: Docker@2
  displayName: Docker Build and Push API
  inputs:
    repository: 'bryht/domino-application'
    command: 'buildAndPush'
    Dockerfile: './src/DominoApplication.Api/Dockerfile'
    buildContext: 'domino-application'
    tags: 'dev'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      $ docker push docker.pkg.github.com/playdomino/domino-application/domino-application:dev



